var NAVTREE_DATA =
[ [ "cyanogenmod.alarmclock", "reference/cyanogenmod/alarmclock/package-summary.html", [ [ "Interfaces", null, [ [ "ClockContract.AlarmsColumns", "reference/cyanogenmod/alarmclock/ClockContract.AlarmsColumns.html", null, "2" ], [ "ClockContract.AlarmSettingColumns", "reference/cyanogenmod/alarmclock/ClockContract.AlarmSettingColumns.html", null, "2" ], [ "ClockContract.CitiesColumns", "reference/cyanogenmod/alarmclock/ClockContract.CitiesColumns.html", null, "2" ], [ "ClockContract.InstancesColumns", "reference/cyanogenmod/alarmclock/ClockContract.InstancesColumns.html", null, "2" ] ]
, null ], [ "Classes", null, [ [ "ClockContract", "reference/cyanogenmod/alarmclock/ClockContract.html", null, "2" ], [ "CyanogenModAlarmClock", "reference/cyanogenmod/alarmclock/CyanogenModAlarmClock.html", null, "2" ] ]
, null ] ]
, "2" ], [ "cyanogenmod.app", "reference/cyanogenmod/app/package-summary.html", [ [ "Classes", null, [ [ "CMStatusBarManager", "reference/cyanogenmod/app/CMStatusBarManager.html", null, "1" ], [ "CMTelephonyManager", "reference/cyanogenmod/app/CMTelephonyManager.html", null, "2" ], [ "CustomTile", "reference/cyanogenmod/app/CustomTile.html", null, "1" ], [ "CustomTile.Builder", "reference/cyanogenmod/app/CustomTile.Builder.html", null, "1" ], [ "CustomTile.ExpandedGridItem", "reference/cyanogenmod/app/CustomTile.ExpandedGridItem.html", null, "1" ], [ "CustomTile.ExpandedItem", "reference/cyanogenmod/app/CustomTile.ExpandedItem.html", null, "1" ], [ "CustomTile.ExpandedListItem", "reference/cyanogenmod/app/CustomTile.ExpandedListItem.html", null, "1" ], [ "CustomTile.ExpandedStyle", "reference/cyanogenmod/app/CustomTile.ExpandedStyle.html", null, "1" ], [ "CustomTile.GridExpandedStyle", "reference/cyanogenmod/app/CustomTile.GridExpandedStyle.html", null, "1" ], [ "CustomTile.ListExpandedStyle", "reference/cyanogenmod/app/CustomTile.ListExpandedStyle.html", null, "1" ], [ "CustomTile.RemoteExpandedStyle", "reference/cyanogenmod/app/CustomTile.RemoteExpandedStyle.html", null, "2" ], [ "CustomTileListenerService", "reference/cyanogenmod/app/CustomTileListenerService.html", null, "1" ], [ "Profile", "reference/cyanogenmod/app/Profile.html", null, "2" ], [ "Profile.DozeMode", "reference/cyanogenmod/app/Profile.DozeMode.html", null, "2" ], [ "Profile.ExpandedDesktopMode", "reference/cyanogenmod/app/Profile.ExpandedDesktopMode.html", null, "2" ], [ "Profile.LockMode", "reference/cyanogenmod/app/Profile.LockMode.html", null, "2" ], [ "Profile.ProfileTrigger", "reference/cyanogenmod/app/Profile.ProfileTrigger.html", null, "2" ], [ "Profile.TriggerState", "reference/cyanogenmod/app/Profile.TriggerState.html", null, "2" ], [ "Profile.TriggerType", "reference/cyanogenmod/app/Profile.TriggerType.html", null, "2" ], [ "Profile.Type", "reference/cyanogenmod/app/Profile.Type.html", null, "2" ], [ "ProfileManager", "reference/cyanogenmod/app/ProfileManager.html", null, "2" ], [ "SettingsManager", "reference/cyanogenmod/app/SettingsManager.html", null, "2" ], [ "StatusBarPanelCustomTile", "reference/cyanogenmod/app/StatusBarPanelCustomTile.html", null, "1" ] ]
, null ] ]
, "1" ], [ "cyanogenmod.hardware", "reference/cyanogenmod/hardware/package-summary.html", [ [ "Classes", null, [ [ "CMHardwareManager", "reference/cyanogenmod/hardware/CMHardwareManager.html", null, "2" ], [ "DisplayMode", "reference/cyanogenmod/hardware/DisplayMode.html", null, "2" ] ]
, null ] ]
, "2" ], [ "cyanogenmod.media", "reference/cyanogenmod/media/package-summary.html", [ [ "Classes", null, [ [ "MediaRecorder", "reference/cyanogenmod/media/MediaRecorder.html", null, "2" ], [ "MediaRecorder.AudioSource", "reference/cyanogenmod/media/MediaRecorder.AudioSource.html", null, "2" ] ]
, null ] ]
, "2" ], [ "cyanogenmod.os", "reference/cyanogenmod/os/package-summary.html", [ [ "Classes", null, [ [ "Build", "reference/cyanogenmod/os/Build.html", null, "1" ], [ "Build.CM_VERSION", "reference/cyanogenmod/os/Build.CM_VERSION.html", null, "1" ], [ "Build.CM_VERSION_CODES", "reference/cyanogenmod/os/Build.CM_VERSION_CODES.html", null, "1" ] ]
, null ] ]
, "1" ], [ "cyanogenmod.platform", "reference/cyanogenmod/platform/package-summary.html", [ [ "Classes", null, [ [ "Manifest", "reference/cyanogenmod/platform/Manifest.html", null, "1" ], [ "Manifest.permission", "reference/cyanogenmod/platform/Manifest.permission.html", null, "1" ], [ "R", "reference/cyanogenmod/platform/R.html", null, "1" ], [ "R.attr", "reference/cyanogenmod/platform/R.attr.html", null, "1" ], [ "R.drawable", "reference/cyanogenmod/platform/R.drawable.html", null, "2" ], [ "R.string", "reference/cyanogenmod/platform/R.string.html", null, "1" ], [ "R.xml", "reference/cyanogenmod/platform/R.xml.html", null, "2" ] ]
, null ] ]
, "1" ], [ "cyanogenmod.profiles", "reference/cyanogenmod/profiles/package-summary.html", [ [ "Classes", null, [ [ "AirplaneModeSettings", "reference/cyanogenmod/profiles/AirplaneModeSettings.html", null, "2" ], [ "AirplaneModeSettings.BooleanState", "reference/cyanogenmod/profiles/AirplaneModeSettings.BooleanState.html", null, "2" ], [ "BrightnessSettings", "reference/cyanogenmod/profiles/BrightnessSettings.html", null, "2" ], [ "ConnectionSettings", "reference/cyanogenmod/profiles/ConnectionSettings.html", null, "2" ], [ "ConnectionSettings.BooleanState", "reference/cyanogenmod/profiles/ConnectionSettings.BooleanState.html", null, "2" ], [ "LockSettings", "reference/cyanogenmod/profiles/LockSettings.html", null, "2" ], [ "RingModeSettings", "reference/cyanogenmod/profiles/RingModeSettings.html", null, "2" ], [ "StreamSettings", "reference/cyanogenmod/profiles/StreamSettings.html", null, "2" ] ]
, null ] ]
, "2" ], [ "cyanogenmod.providers", "reference/cyanogenmod/providers/package-summary.html", [ [ "Classes", null, [ [ "CMSettings", "reference/cyanogenmod/providers/CMSettings.html", null, "2" ], [ "CMSettings.Global", "reference/cyanogenmod/providers/CMSettings.Global.html", null, "2" ], [ "CMSettings.Secure", "reference/cyanogenmod/providers/CMSettings.Secure.html", null, "2" ], [ "CMSettings.System", "reference/cyanogenmod/providers/CMSettings.System.html", null, "2" ] ]
, null ], [ "Exceptions", null, [ [ "CMSettings.CMSettingNotFoundException", "reference/cyanogenmod/providers/CMSettings.CMSettingNotFoundException.html", null, "2" ] ]
, null ] ]
, "2" ] ]

;

