var DATA = [
      { id:0, label:"cyanogenmod.app", link:"reference/cyanogenmod/app/package-summary.html", type:"package", deprecated:"false" },
      { id:1, label:"cyanogenmod.app.CMStatusBarManager", link:"reference/cyanogenmod/app/CMStatusBarManager.html", type:"class", deprecated:"false" },
      { id:2, label:"cyanogenmod.app.CustomTile", link:"reference/cyanogenmod/app/CustomTile.html", type:"class", deprecated:"false" },
      { id:3, label:"cyanogenmod.app.CustomTile.Builder", link:"reference/cyanogenmod/app/CustomTile.Builder.html", type:"class", deprecated:"false" },
      { id:4, label:"cyanogenmod.app.CustomTile.ExpandedGridItem", link:"reference/cyanogenmod/app/CustomTile.ExpandedGridItem.html", type:"class", deprecated:"false" },
      { id:5, label:"cyanogenmod.app.CustomTile.ExpandedItem", link:"reference/cyanogenmod/app/CustomTile.ExpandedItem.html", type:"class", deprecated:"false" },
      { id:6, label:"cyanogenmod.app.CustomTile.ExpandedListItem", link:"reference/cyanogenmod/app/CustomTile.ExpandedListItem.html", type:"class", deprecated:"false" },
      { id:7, label:"cyanogenmod.app.CustomTile.ExpandedStyle", link:"reference/cyanogenmod/app/CustomTile.ExpandedStyle.html", type:"class", deprecated:"false" },
      { id:8, label:"cyanogenmod.app.CustomTile.GridExpandedStyle", link:"reference/cyanogenmod/app/CustomTile.GridExpandedStyle.html", type:"class", deprecated:"false" },
      { id:9, label:"cyanogenmod.app.CustomTile.ListExpandedStyle", link:"reference/cyanogenmod/app/CustomTile.ListExpandedStyle.html", type:"class", deprecated:"false" },
      { id:10, label:"cyanogenmod.app.CustomTileListenerService", link:"reference/cyanogenmod/app/CustomTileListenerService.html", type:"class", deprecated:"false" },
      { id:11, label:"cyanogenmod.app.StatusBarPanelCustomTile", link:"reference/cyanogenmod/app/StatusBarPanelCustomTile.html", type:"class", deprecated:"false" },
      { id:12, label:"cyanogenmod.os", link:"reference/cyanogenmod/os/package-summary.html", type:"package", deprecated:"false" },
      { id:13, label:"cyanogenmod.os.Build", link:"reference/cyanogenmod/os/Build.html", type:"class", deprecated:"false" },
      { id:14, label:"cyanogenmod.os.Build.CM_VERSION", link:"reference/cyanogenmod/os/Build.CM_VERSION.html", type:"class", deprecated:"false" },
      { id:15, label:"cyanogenmod.os.Build.CM_VERSION_CODES", link:"reference/cyanogenmod/os/Build.CM_VERSION_CODES.html", type:"class", deprecated:"false" },
      { id:16, label:"cyanogenmod.platform", link:"reference/cyanogenmod/platform/package-summary.html", type:"package", deprecated:"false" },
      { id:17, label:"cyanogenmod.platform.Manifest", link:"reference/cyanogenmod/platform/Manifest.html", type:"class", deprecated:"false" },
      { id:18, label:"cyanogenmod.platform.Manifest.permission", link:"reference/cyanogenmod/platform/Manifest.permission.html", type:"class", deprecated:"false" },
      { id:19, label:"cyanogenmod.platform.R", link:"reference/cyanogenmod/platform/R.html", type:"class", deprecated:"false" },
      { id:20, label:"cyanogenmod.platform.R.attr", link:"reference/cyanogenmod/platform/R.attr.html", type:"class", deprecated:"false" },
      { id:21, label:"cyanogenmod.platform.R.string", link:"reference/cyanogenmod/platform/R.string.html", type:"class", deprecated:"false" }

    ];
